import Link from "next/link";
import Providers from "./providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <header className="flex space-x-4 items-center justify-center p-4">
            <Link href="/">Home</Link>
            <Link href="/rq-super-heroes">RQ Super Heroes</Link>
            <Link href="/super-heroes">Super Heroes</Link>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
