import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <nav>
          <Link href={'./'}>Home</Link>
          <Link href='./users'>Users</Link>
          <Link href='./users/4432'>User 4432</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
